// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import isc "git.zam.io/wallet-backend/wallet-api/internal/services/isc"
import mock "github.com/stretchr/testify/mock"

// ITxsEventNotificator is an autogenerated mock type for the ITxsEventNotificator type
type ITxsEventNotificator struct {
	mock.Mock
}

// AwaitRecipient provides a mock function with given fields: payload
func (_m *ITxsEventNotificator) AwaitRecipient(payload isc.TxEventPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(isc.TxEventPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Declined provides a mock function with given fields: payload, declineReason
func (_m *ITxsEventNotificator) Declined(payload isc.TxEventPayload, declineReason error) error {
	ret := _m.Called(payload, declineReason)

	var r0 error
	if rf, ok := ret.Get(0).(func(isc.TxEventPayload, error) error); ok {
		r0 = rf(payload, declineReason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Processed provides a mock function with given fields: payload
func (_m *ITxsEventNotificator) Processed(payload isc.TxEventPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(isc.TxEventPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
