// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// IGenerator is an autogenerated mock type for the IGenerator type
type IGenerator struct {
	mock.Mock
}

// Create provides a mock function with given fields: coin, seed
func (_m *IGenerator) Create(coin string, seed string) (string, string, error) {
	ret := _m.Called(coin, seed)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(coin, seed)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(coin, seed)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(coin, seed)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
