// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import decimal "github.com/ericlagergren/decimal"
import mock "github.com/stretchr/testify/mock"

// IAccountObserver is an autogenerated mock type for the IAccountObserver type
type IAccountObserver struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx
func (_m *IAccountObserver) GetBalance(ctx context.Context) (*decimal.Big, error) {
	ret := _m.Called(ctx)

	var r0 *decimal.Big
	if rf, ok := ret.Get(0).(func(context.Context) *decimal.Big); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*decimal.Big)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
