// Code generated by mockery v1.0.0
package mocks

import context "context"
import decimal "github.com/ericlagergren/decimal"
import mock "github.com/stretchr/testify/mock"

// ITxSender is an autogenerated mock type for the ITxSender type
type ITxSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, fromAddress, toAddress, amount
func (_m *ITxSender) Send(ctx context.Context, fromAddress string, toAddress string, amount *decimal.Big) (string, *decimal.Big, error) {
	ret := _m.Called(ctx, fromAddress, toAddress, amount)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *decimal.Big) string); ok {
		r0 = rf(ctx, fromAddress, toAddress, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 *decimal.Big
	if rf, ok := ret.Get(1).(func(context.Context, string, string, *decimal.Big) *decimal.Big); ok {
		r1 = rf(ctx, fromAddress, toAddress, amount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*decimal.Big)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, *decimal.Big) error); ok {
		r2 = rf(ctx, fromAddress, toAddress, amount)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SupportInternalTxs provides a mock function with given fields:
func (_m *ITxSender) SupportInternalTxs() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
